version: '3.7'

services:
  frontend:
    container_name: frontend-con
    # Dockerfile의 경로
    build: ./frontend
    command: ['yarn', 'start']
    ports:
      - 3000:3000
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리(작업공간 frontend로 설정해줌 -> frontend/Dockerfile)
    volumes:
      - ./frontend:/frontend
    # docker container 특성상 커맨드 끝나면 컨테이너가 종료되는데 이를 방지하기 위해 tty 옵션 추가
    tty: true

    # networks:
    #   - app-tier

  backend:
    container_name: backend-con
    build:
      context: ./backend
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./backend:/backend/
    # restart: always 배포때만
    env_file:
      - ./.env
    depends_on:
      - db
    # command: 
    networks:
      - app-tier
    # 명령어 실행 끝나도 안꺼짐
    tty: true
  
  db:
    image: mysql
    platform: linux/amd64
    container_name: mysql-con
    env_file:
      - ./.env
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - data_mysql:/mysql
    networks:
      - app-tier
    # 명령어 실행 끝나도 안꺼짐
    tty: true


  nginx:
    image: nginx:1.21.5-alpine
    build: ./nginx
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./nginx/nginx.conf:/nginx/nginx.conf
    container_name: nginx-con
    depends_on:
      - frontend
      - backend
    # networks:
    #   - app-tier
    tty: true

networks:
  localnetwork:
    external: true

volumes:
  data_mysql:
  build_folder:
#fastAPI, Uvicorn, Firebase,
